package parties

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/uptrace/bun"
)

// CreatePartyInput is the data needed to create a party. The info token is
// always generated by the service (never supplied), so it is absent here. The
// RSVP code is optional: when nil the service leaves it unset, when set it must
// be unique.
//
// Address fields are optional at creation; whether they are *required* is a
// status concern (physical parties), not a creation precondition, so an
// under-filled party can be created and simply reads as incomplete.
type CreatePartyInput struct {
	Name            string
	Side            string
	Relation        string
	Circle          []string
	InvitationType  string
	AddressLine1    *string
	AddressLine2    *string
	City            *string
	StateOrProvince *string
	PostalCode      *string
	Country         *string
	RSVPCode        *string
}

// UpdatePartyInput is the full desired state of a party's editable fields. The
// update replaces these fields wholesale (a PUT-style update). It deliberately
// excludes info_token (immutable once generated) and the two
// info_collection_* flags: editing info fields must never change collection
// status (ADR 0005), so those flags move only through the dedicated transition
// methods.
type UpdatePartyInput struct {
	Name            string
	Side            string
	Relation        string
	Circle          []string
	InvitationType  string
	AddressLine1    *string
	AddressLine2    *string
	City            *string
	StateOrProvince *string
	PostalCode      *string
	Country         *string
	RSVPCode        *string
}

// CreateParty validates and inserts a party, generating a unique info token. A
// supplied RSVP code that is already taken yields ErrConflict.
func (s *Service) CreateParty(ctx context.Context, in CreatePartyInput) (*Party, error) {
	if err := validatePartyEnums(in.Side, in.Relation, in.InvitationType); err != nil {
		return nil, fmt.Errorf("%w: %s", ErrValidation, err.Error())
	}
	if strings.TrimSpace(in.Name) == "" {
		return nil, validationErr("name is required")
	}

	now := time.Now()
	party := &Party{
		ID:              newID(),
		Name:            strings.TrimSpace(in.Name),
		Side:            in.Side,
		Relation:        in.Relation,
		Circle:          normalizeStringSlice(in.Circle),
		InvitationType:  in.InvitationType,
		AddressLine1:    trimmedOrNil(in.AddressLine1),
		AddressLine2:    trimmedOrNil(in.AddressLine2),
		City:            trimmedOrNil(in.City),
		StateOrProvince: trimmedOrNil(in.StateOrProvince),
		PostalCode:      trimmedOrNil(in.PostalCode),
		Country:         trimmedOrNil(in.Country),
		RSVPCode:        trimmedOrNil(in.RSVPCode),
		CreatedAt:       now,
		UpdatedAt:       now,
	}

	// Generate a unique info token, retrying only on a token collision. Any
	// other unique conflict (the RSVP code) is the caller's input and is
	// reported as ErrConflict immediately rather than retried.
	for attempt := 0; attempt < maxTokenAttempts; attempt++ {
		token, err := generateInfoToken()
		if err != nil {
			return nil, err
		}
		party.InfoToken = token

		_, err = s.db.NewInsert().Model(party).Exec(ctx)
		if err == nil {
			return party, nil
		}
		if isUniqueViolation(err) {
			// Distinguish an RSVP-code conflict (caller's fault, do not retry)
			// from an info-token collision (retry with a new token).
			if in.RSVPCode != nil && isRSVPCodeConflict(ctx, s.db, party.RSVPCode) {
				return nil, ErrConflict
			}
			continue
		}
		return nil, fmt.Errorf("insert party: %w", err)
	}
	return nil, fmt.Errorf("generate unique info token: exhausted %d attempts", maxTokenAttempts)
}

// GetParty loads a single party with its guests, or ErrNotFound.
func (s *Service) GetParty(ctx context.Context, id string) (*Party, error) {
	return loadPartyWithGuests(ctx, s.db, id)
}

// UpdateParty applies the editable fields to an existing party. It does not
// touch info_token or the info_collection_* flags (status transitions go
// through their own methods). A duplicate RSVP code yields ErrConflict, a
// missing party ErrNotFound.
func (s *Service) UpdateParty(ctx context.Context, id string, in UpdatePartyInput) (*Party, error) {
	if err := validatePartyEnums(in.Side, in.Relation, in.InvitationType); err != nil {
		return nil, fmt.Errorf("%w: %s", ErrValidation, err.Error())
	}
	if strings.TrimSpace(in.Name) == "" {
		return nil, validationErr("name is required")
	}

	party, err := loadPartyWithGuests(ctx, s.db, id)
	if err != nil {
		return nil, err
	}

	party.Name = strings.TrimSpace(in.Name)
	party.Side = in.Side
	party.Relation = in.Relation
	party.Circle = normalizeStringSlice(in.Circle)
	party.InvitationType = in.InvitationType
	party.AddressLine1 = trimmedOrNil(in.AddressLine1)
	party.AddressLine2 = trimmedOrNil(in.AddressLine2)
	party.City = trimmedOrNil(in.City)
	party.StateOrProvince = trimmedOrNil(in.StateOrProvince)
	party.PostalCode = trimmedOrNil(in.PostalCode)
	party.Country = trimmedOrNil(in.Country)
	party.RSVPCode = trimmedOrNil(in.RSVPCode)
	party.UpdatedAt = time.Now()

	// Update only the editable columns. info_token and the info_collection_*
	// flags are intentionally excluded from the SET list so a field edit can
	// never alter the collection status.
	_, err = s.db.NewUpdate().Model(party).
		Column("name", "side", "relation", "circle", "invitation_type",
			"address_line_1", "address_line_2", "city", "state_or_province",
			"postal_code", "country", "rsvp_code", "updated_at").
		WherePK().Exec(ctx)
	if err != nil {
		if isUniqueViolation(err) {
			return nil, ErrConflict
		}
		return nil, fmt.Errorf("update party: %w", err)
	}
	return party, nil
}

// DeleteParty removes a party. Its guests are removed by the FK cascade.
// Deleting a non-existent party returns ErrNotFound.
func (s *Service) DeleteParty(ctx context.Context, id string) error {
	res, err := s.db.NewDelete().Model((*Party)(nil)).Where("id = ?", id).Exec(ctx)
	if err != nil {
		return fmt.Errorf("delete party: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("delete party rows affected: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// isRSVPCodeConflict reports whether a party (other than none) already holds the
// given RSVP code. It is used to classify a unique violation during create as an
// RSVP-code conflict versus an info-token collision.
func isRSVPCodeConflict(ctx context.Context, db bun.IDB, code *string) bool {
	if code == nil {
		return false
	}
	exists, err := db.NewSelect().Model((*Party)(nil)).Where("rsvp_code = ?", *code).Exists(ctx)
	if err != nil {
		return false
	}
	return exists
}

// normalizeStringSlice guarantees a non-nil slice (so a text[] column stores an
// empty array, never NULL) and trims blank entries. Order is preserved.
func normalizeStringSlice(in []string) []string {
	out := make([]string, 0, len(in))
	for _, v := range in {
		if t := strings.TrimSpace(v); t != "" {
			out = append(out, t)
		}
	}
	return out
}
