package parties

import "github.com/robinjoseph08/robinandmadeline.com/pkg/models"

// This file is the single home for the package's request, response, query, and
// enum-carrying payload types (#341): handlers never use anonymous structs,
// echo.Map, or map[string]any. Each payload doubles as the service input.

// CreatePartyPayload is the body for creating a party. The info token is always
// generated by the service (never supplied). The RSVP code is optional: when nil
// it is left unset, when set it must be unique. Address fields are optional at
// creation; whether they are required is a status concern, not a creation
// precondition, so an under-filled party can be created and reads incomplete.
type CreatePartyPayload struct {
	Name            string   `json:"name"`
	Side            string   `json:"side" tstype:"models.Side"`
	Relation        string   `json:"relation" tstype:"models.Relation"`
	Circle          []string `json:"circle" tstype:"models.Circle[]"`
	InvitationType  string   `json:"invitation_type" tstype:"models.InvitationType"`
	AddressLine1    *string  `json:"address_line_1"`
	AddressLine2    *string  `json:"address_line_2"`
	City            *string  `json:"city"`
	StateOrProvince *string  `json:"state_or_province"`
	PostalCode      *string  `json:"postal_code"`
	Country         *string  `json:"country"`
	RSVPCode        *string  `json:"rsvp_code"`
}

// UpdatePartyPayload is the full desired state of a party's editable fields
// (PUT-style). It excludes info_token (immutable) and the info_collection_*
// flags: editing info fields must never change collection status (ADR 0005), so
// those move only through the transition endpoints.
type UpdatePartyPayload struct {
	Name            string   `json:"name"`
	Side            string   `json:"side" tstype:"models.Side"`
	Relation        string   `json:"relation" tstype:"models.Relation"`
	Circle          []string `json:"circle" tstype:"models.Circle[]"`
	InvitationType  string   `json:"invitation_type" tstype:"models.InvitationType"`
	AddressLine1    *string  `json:"address_line_1"`
	AddressLine2    *string  `json:"address_line_2"`
	City            *string  `json:"city"`
	StateOrProvince *string  `json:"state_or_province"`
	PostalCode      *string  `json:"postal_code"`
	Country         *string  `json:"country"`
	RSVPCode        *string  `json:"rsvp_code"`
}

// MarkInfoPayload is the body of mark-info, selecting the target status. status
// must be StatusComplete or StatusIncomplete.
type MarkInfoPayload struct {
	Status string `json:"status" tstype:"models.InfoCollectionStatus"`
}

// ListPartiesQuery is the set of party list filters. A nil pointer (or empty
// value) means "do not filter on this field". Every filter except
// InfoCollectionStatus is applied in SQL; status is computed in Go (it depends
// on the derived rules) and filtered after the query.
type ListPartiesQuery struct {
	Side                    *string `json:"side"`
	Relation                *string `json:"relation"`
	Circle                  *string `json:"circle"` // matches parties whose circle array contains this value
	InvitationType          *string `json:"invitation_type"`
	InfoCollectionRequested *bool   `json:"info_collection_requested"`
	InfoCollectionStatus    *string `json:"info_collection_status" tstype:"models.InfoCollectionStatus"`
}

// CreateGuestPayload is the body to add a guest to a party. The party comes from
// the route (create is nested under the party), so it is not a field here.
// is_primary may be requested; when true the service demotes any existing
// primary in the same transaction.
type CreateGuestPayload struct {
	FullName            string   `json:"full_name"`
	Email               *string  `json:"email"`
	Phone               *string  `json:"phone"`
	Roles               []string `json:"roles"`
	IsPrimary           bool     `json:"is_primary"`
	IsChild             bool     `json:"is_child"`
	IsDrinking          bool     `json:"is_drinking"`
	IsPlaceholder       bool     `json:"is_placeholder"`
	DietaryRestrictions *string  `json:"dietary_restrictions"`
	TableNumber         *int     `json:"table_number"`
	SeatNumber          *int     `json:"seat_number"`
}

// UpdateGuestPayload is the full desired state of a guest's editable fields
// (PUT-style). Setting IsPrimary=true promotes this guest and demotes the
// party's previous primary transactionally.
type UpdateGuestPayload struct {
	FullName            string   `json:"full_name"`
	Email               *string  `json:"email"`
	Phone               *string  `json:"phone"`
	Roles               []string `json:"roles"`
	IsPrimary           bool     `json:"is_primary"`
	IsChild             bool     `json:"is_child"`
	IsDrinking          bool     `json:"is_drinking"`
	IsPlaceholder       bool     `json:"is_placeholder"`
	DietaryRestrictions *string  `json:"dietary_restrictions"`
	TableNumber         *int     `json:"table_number"`
	SeatNumber          *int     `json:"seat_number"`
}

// ListGuestsQuery is the set of flat guest-list filters. Side / Relation /
// Circle are party-level attributes, so those clauses join through the guest's
// party. Event- and RSVP-status filters are absent: they depend on the event
// model (#6) which does not exist yet.
type ListGuestsQuery struct {
	Side          *string `json:"side"`
	Relation      *string `json:"relation"`
	Circle        *string `json:"circle"`
	Roles         *string `json:"roles"` // matches guests whose roles array contains this value
	IsDrinking    *bool   `json:"is_drinking"`
	IsChild       *bool   `json:"is_child"`
	IsPlaceholder *bool   `json:"is_placeholder"`
}

// PartyResponse is the API representation of a party: the stored model plus the
// derived info_collection_status. The embedded *models.Party already carries
// snake_case JSON tags and is flattened into the TS interface via ",extends".
type PartyResponse struct {
	*models.Party        `tstype:",extends"`
	InfoCollectionStatus string `json:"info_collection_status" tstype:"models.InfoCollectionStatus"`
}

// ListPartiesResponse is the uniform list envelope for parties.
type ListPartiesResponse struct {
	Items []PartyResponse `json:"items"`
	Total int             `json:"total"`
}

// GuestResponse is the API representation of a guest. No reshape is needed, so
// it is a thin embed of the stored model.
type GuestResponse struct {
	*models.Guest `tstype:",extends"`
}

// ListGuestsResponse is the uniform list envelope for guests.
type ListGuestsResponse struct {
	Items []GuestResponse `json:"items"`
	Total int             `json:"total"`
}

// newPartyResponse wraps a loaded party (with guests) for the API, computing its
// status. Guests must be loaded for the status to be accurate.
func newPartyResponse(p *models.Party) PartyResponse {
	return PartyResponse{Party: p, InfoCollectionStatus: p.InfoCollectionStatus()}
}

// newGuestResponse wraps a guest for the API.
func newGuestResponse(g *models.Guest) GuestResponse {
	return GuestResponse{Guest: g}
}
