package parties

import "github.com/robinjoseph08/robinandmadeline.com/pkg/models"

// This file is the single home for the package's request, response, query, and
// enum-carrying payload types (#341): handlers never use anonymous structs,
// echo.Map, or map[string]any. Each payload doubles as the service input.

// CreatePartyPayload is the body for creating a party. The info token is always
// generated by the service (never supplied). The RSVP code is optional: when nil
// it is left unset, when set it must be unique. Address fields are optional at
// creation; whether they are required is a status concern, not a creation
// precondition, so an under-filled party can be created and reads incomplete.
//
// Validation is tag-driven through the custom binder (pkg/binder): `mod` trims,
// `default` fills, `validate` checks. rsvp_code uses min=1 deliberately: a
// present-but-blank value is a 422, while "no code" must arrive as JSON null so
// it persists as SQL NULL and the partial unique index keeps allowing many
// code-less parties. circle defaults to [] so a nil slice stores '{}', not NULL.
type CreatePartyPayload struct {
	Name            string   `json:"name" mod:"trim" validate:"required,max=200"`
	Side            string   `json:"side" validate:"required,oneof=robin madeline" tstype:"models.Side"`
	Relation        string   `json:"relation" validate:"required,oneof=family friend" tstype:"models.Relation"`
	Circle          []string `json:"circle" mod:"dive,trim" validate:"omitempty,dive,oneof=Immediate Extended College Work Childhood Other" default:"[]" tstype:"models.Circle[]"`
	InvitationType  string   `json:"invitation_type" validate:"required,oneof=physical digital" tstype:"models.InvitationType"`
	AddressLine1    *string  `json:"address_line_1" mod:"trim" validate:"omitempty,max=200"`
	AddressLine2    *string  `json:"address_line_2" mod:"trim" validate:"omitempty,max=200"`
	City            *string  `json:"city" mod:"trim" validate:"omitempty,max=200"`
	StateOrProvince *string  `json:"state_or_province" mod:"trim" validate:"omitempty,max=200"`
	PostalCode      *string  `json:"postal_code" mod:"trim" validate:"omitempty,max=200"`
	Country         *string  `json:"country" mod:"trim" validate:"omitempty,max=200"`
	RSVPCode        *string  `json:"rsvp_code" mod:"trim" validate:"omitempty,min=1,max=64"`
}

// UpdatePartyPayload is the full desired state of a party's editable fields
// (PUT-style). It excludes info_token (immutable) and the info_collection_*
// flags: editing info fields must never change collection status (ADR 0005), so
// those move only through the transition endpoints. Validation mirrors
// CreatePartyPayload and is tag-driven through the custom binder.
type UpdatePartyPayload struct {
	Name            string   `json:"name" mod:"trim" validate:"required,max=200"`
	Side            string   `json:"side" validate:"required,oneof=robin madeline" tstype:"models.Side"`
	Relation        string   `json:"relation" validate:"required,oneof=family friend" tstype:"models.Relation"`
	Circle          []string `json:"circle" mod:"dive,trim" validate:"omitempty,dive,oneof=Immediate Extended College Work Childhood Other" default:"[]" tstype:"models.Circle[]"`
	InvitationType  string   `json:"invitation_type" validate:"required,oneof=physical digital" tstype:"models.InvitationType"`
	AddressLine1    *string  `json:"address_line_1" mod:"trim" validate:"omitempty,max=200"`
	AddressLine2    *string  `json:"address_line_2" mod:"trim" validate:"omitempty,max=200"`
	City            *string  `json:"city" mod:"trim" validate:"omitempty,max=200"`
	StateOrProvince *string  `json:"state_or_province" mod:"trim" validate:"omitempty,max=200"`
	PostalCode      *string  `json:"postal_code" mod:"trim" validate:"omitempty,max=200"`
	Country         *string  `json:"country" mod:"trim" validate:"omitempty,max=200"`
	RSVPCode        *string  `json:"rsvp_code" mod:"trim" validate:"omitempty,min=1,max=64"`
}

// PatchPartyPayload is a partial update of a party's editable fields: a nil
// pointer (an absent JSON key) leaves that column unchanged, while a provided
// field is applied. It backs the spreadsheet's single-cell edits (PATCH), where
// saving a cell touches only the field the user changed; the PUT full-state
// payload (UpdatePartyPayload) backs the dialog "full edit". Like
// UpdatePartyPayload it can never alter info_token or the info_collection_*
// flags (ADR 0005): the service excludes those columns.
//
// Validation is tag-driven and uniformly omitempty, so an absent field is
// skipped while a provided one is normalized (mod) then validated. validator
// treats a non-nil pointer as present even when it points at an empty string, so
// a provided-but-blank required field is still rejected: name carries min=1, so
// blanking the name cell is a 422. The nullable text fields instead permit blank
// (max-only, plus emailblank-style format checks elsewhere) because a provided
// blank is the grid's "clear this cell" gesture, which the service stores as SQL
// NULL (so a cleared rsvp_code leaves the partial unique index rather than
// colliding on ""). circle is a plain slice (not a pointer): nil leaves it
// unchanged, a present array (including []) replaces it.
type PatchPartyPayload struct {
	Name            *string  `json:"name,omitempty" mod:"trim" validate:"omitempty,min=1,max=200"`
	Side            *string  `json:"side,omitempty" validate:"omitempty,oneof=robin madeline" tstype:"models.Side"`
	Relation        *string  `json:"relation,omitempty" validate:"omitempty,oneof=family friend" tstype:"models.Relation"`
	Circle          []string `json:"circle,omitempty" mod:"dive,trim" validate:"omitempty,dive,oneof=Immediate Extended College Work Childhood Other" tstype:"models.Circle[]"`
	InvitationType  *string  `json:"invitation_type,omitempty" validate:"omitempty,oneof=physical digital" tstype:"models.InvitationType"`
	AddressLine1    *string  `json:"address_line_1,omitempty" mod:"trim" validate:"omitempty,max=200"`
	AddressLine2    *string  `json:"address_line_2,omitempty" mod:"trim" validate:"omitempty,max=200"`
	City            *string  `json:"city,omitempty" mod:"trim" validate:"omitempty,max=200"`
	StateOrProvince *string  `json:"state_or_province,omitempty" mod:"trim" validate:"omitempty,max=200"`
	PostalCode      *string  `json:"postal_code,omitempty" mod:"trim" validate:"omitempty,max=200"`
	Country         *string  `json:"country,omitempty" mod:"trim" validate:"omitempty,max=200"`
	RSVPCode        *string  `json:"rsvp_code,omitempty" mod:"trim" validate:"omitempty,max=64"`
}

// MarkInfoPayload is the body of mark-info, selecting the target status. status
// must be StatusComplete or StatusIncomplete; the binder enforces the enum.
type MarkInfoPayload struct {
	Status string `json:"status" validate:"required,oneof=complete incomplete" tstype:"models.InfoCollectionStatus"`
}

// ListPartiesQuery is the set of party list filters, bound from the query string
// by the custom binder (gorilla/schema via the `query` tag). A nil pointer means
// "do not filter on this field". Every filter except InfoCollectionStatus is
// applied in SQL; status is computed in Go (it depends on the derived rules) and
// filtered after the query. Enum filters are validated (omitempty so an absent
// filter is fine); a bad value is a 422.
type ListPartiesQuery struct {
	Side                    *string `query:"side" json:"side" validate:"omitempty,oneof=robin madeline"`
	Relation                *string `query:"relation" json:"relation" validate:"omitempty,oneof=family friend"`
	Circle                  *string `query:"circle" json:"circle"` // matches parties whose circle array contains this value
	InvitationType          *string `query:"invitation_type" json:"invitation_type" validate:"omitempty,oneof=physical digital"`
	InfoCollectionRequested *bool   `query:"info_collection_requested" json:"info_collection_requested"`
	InfoCollectionStatus    *string `query:"info_collection_status" json:"info_collection_status" validate:"omitempty,oneof=complete incomplete" tstype:"models.InfoCollectionStatus"`
}

// CreateGuestPayload is the body to add a guest to a party. The party comes from
// the route (create is nested under the party), so it is not a field here.
// is_primary may be requested; when true the service demotes any existing
// primary in the same transaction. Validation is tag-driven through the custom
// binder. tags is open-ended (no closed union) so it only bounds element
// length; it defaults to [] so a nil slice stores '{}', not NULL.
type CreateGuestPayload struct {
	FullName            string   `json:"full_name" mod:"trim" validate:"required,max=200"`
	Email               *string  `json:"email" mod:"trim" validate:"omitempty,email,max=320"`
	Phone               *string  `json:"phone" mod:"trim" validate:"omitempty,max=32"`
	Tags                []string `json:"tags" mod:"dive,trim" validate:"omitempty,dive,min=1,max=100" default:"[]"`
	IsPrimary           bool     `json:"is_primary"`
	IsChild             bool     `json:"is_child"`
	IsDrinking          bool     `json:"is_drinking"`
	IsPlaceholder       bool     `json:"is_placeholder"`
	DietaryRestrictions *string  `json:"dietary_restrictions" mod:"trim" validate:"omitempty,max=1000"`
	TableNumber         *int     `json:"table_number" validate:"omitempty,min=1"`
	SeatNumber          *int     `json:"seat_number" validate:"omitempty,min=1"`
}

// UpdateGuestPayload is the full desired state of a guest's editable fields
// (PUT-style). Setting IsPrimary=true promotes this guest and demotes the
// party's previous primary transactionally. Validation mirrors
// CreateGuestPayload and is tag-driven through the custom binder.
type UpdateGuestPayload struct {
	FullName            string   `json:"full_name" mod:"trim" validate:"required,max=200"`
	Email               *string  `json:"email" mod:"trim" validate:"omitempty,email,max=320"`
	Phone               *string  `json:"phone" mod:"trim" validate:"omitempty,max=32"`
	Tags                []string `json:"tags" mod:"dive,trim" validate:"omitempty,dive,min=1,max=100" default:"[]"`
	IsPrimary           bool     `json:"is_primary"`
	IsChild             bool     `json:"is_child"`
	IsDrinking          bool     `json:"is_drinking"`
	IsPlaceholder       bool     `json:"is_placeholder"`
	DietaryRestrictions *string  `json:"dietary_restrictions" mod:"trim" validate:"omitempty,max=1000"`
	TableNumber         *int     `json:"table_number" validate:"omitempty,min=1"`
	SeatNumber          *int     `json:"seat_number" validate:"omitempty,min=1"`
}

// PatchGuestPayload is a partial update of a guest's editable fields, the guest
// analogue of PatchPartyPayload: a nil pointer (an absent JSON key) leaves that
// column unchanged, while a provided field is applied. It backs the
// spreadsheet's single-cell guest edits (PATCH); the PUT full-state payload
// (UpdateGuestPayload) backs the dialog "full edit". Setting is_primary=true
// promotes this guest and demotes the party's previous primary transactionally.
//
// Validation is uniformly omitempty: an absent field is skipped, full_name keeps
// min=1 so blanking the name cell is a 422, and email uses emailblank so a
// provided blank clears it (the service stores NULL) while a present value is
// still format-checked. tags is a plain slice: nil leaves it unchanged, a
// present array (including []) replaces it. party_id moves the guest to another
// party (the flat guest list edits it inline); the service checks the target
// party exists and keeps the single-primary invariant in the destination.
type PatchGuestPayload struct {
	PartyID             *string  `json:"party_id,omitempty" validate:"omitempty,uuid"`
	FullName            *string  `json:"full_name,omitempty" mod:"trim" validate:"omitempty,min=1,max=200"`
	Email               *string  `json:"email,omitempty" mod:"trim" validate:"omitempty,emailblank,max=320"`
	Phone               *string  `json:"phone,omitempty" mod:"trim" validate:"omitempty,max=32"`
	Tags                []string `json:"tags,omitempty" mod:"dive,trim" validate:"omitempty,dive,min=1,max=100"`
	IsPrimary           *bool    `json:"is_primary,omitempty"`
	IsChild             *bool    `json:"is_child,omitempty"`
	IsDrinking          *bool    `json:"is_drinking,omitempty"`
	IsPlaceholder       *bool    `json:"is_placeholder,omitempty"`
	DietaryRestrictions *string  `json:"dietary_restrictions,omitempty" mod:"trim" validate:"omitempty,max=1000"`
	TableNumber         *int     `json:"table_number,omitempty" validate:"omitempty,min=1"`
	SeatNumber          *int     `json:"seat_number,omitempty" validate:"omitempty,min=1"`
}

// ListGuestsQuery is the set of flat guest-list filters, bound from the query
// string by the custom binder (gorilla/schema via the `query` tag). Side /
// Relation / Circle are party-level attributes, so those clauses join through
// the guest's party. Event- and RSVP-status filters are absent: they depend on
// the event model (#6) which does not exist yet.
type ListGuestsQuery struct {
	Side          *string `query:"side" json:"side" validate:"omitempty,oneof=robin madeline"`
	Relation      *string `query:"relation" json:"relation" validate:"omitempty,oneof=family friend"`
	Circle        *string `query:"circle" json:"circle"`
	Tags          *string `query:"tags" json:"tags"` // matches guests whose tags array contains this value
	IsDrinking    *bool   `query:"is_drinking" json:"is_drinking"`
	IsChild       *bool   `query:"is_child" json:"is_child"`
	IsPlaceholder *bool   `query:"is_placeholder" json:"is_placeholder"`
}

// PartyResponse is the API representation of a party: the stored model plus the
// derived info_collection_status. The model is embedded by value (not as a
// pointer) so tygo flattens it into a plain `extends models.Party`; a pointer
// embed would generate `extends Partial<models.Party>`, making every model field
// optional on the client and defeating the point of the generated types. The
// embedded models.Party already carries the snake_case JSON tags.
type PartyResponse struct {
	models.Party         `tstype:",extends"`
	InfoCollectionStatus string `json:"info_collection_status" tstype:"models.InfoCollectionStatus"`
}

// ListPartiesResponse is the uniform list envelope for parties.
type ListPartiesResponse struct {
	Items []PartyResponse `json:"items"`
	Total int             `json:"total"`
}

// GuestResponse is the API representation of a single guest, used by the
// party-scoped create/update endpoints. No reshape is needed, so it is a thin
// embed of the stored model (by value, so tygo emits a plain `extends
// models.Guest` rather than a Partial; see PartyResponse).
type GuestResponse struct {
	models.Guest `tstype:",extends"`
}

// GuestListItem is the API representation of a guest in the flat guest list. A
// guest is a sub-entity of its party and has no detail page of its own, so the
// list carries the owning party's name (alongside the model's party_id) to let
// the UI link each guest back to its party and edit it in place. It embeds the
// guest model by value (a plain `extends models.Guest`; see PartyResponse) and
// adds only the derived party_name.
type GuestListItem struct {
	models.Guest `tstype:",extends"`
	PartyName    string `json:"party_name"`
}

// ListGuestsResponse is the uniform list envelope for the flat guest list. Items
// are GuestListItem (guest plus party_name), not GuestResponse, because the flat
// list needs the party context the party-scoped endpoints already have.
type ListGuestsResponse struct {
	Items []GuestListItem `json:"items"`
	Total int             `json:"total"`
}

// newPartyResponse wraps a loaded party (with guests) for the API, computing its
// status. Guests must be loaded for the status to be accurate. The status is
// computed before the model is copied into the response by value.
func newPartyResponse(p *models.Party) PartyResponse {
	return PartyResponse{Party: *p, InfoCollectionStatus: p.InfoCollectionStatus()}
}

// newGuestResponse wraps a guest for the API.
func newGuestResponse(g *models.Guest) GuestResponse {
	return GuestResponse{Guest: *g}
}

// newGuestListItem wraps a guest for the flat guest list, carrying the owning
// party's name. The guest's Party relation must be loaded; a guest with no
// loaded party falls back to an empty name rather than panicking.
func newGuestListItem(g *models.Guest) GuestListItem {
	item := GuestListItem{Guest: *g}
	if g.Party != nil {
		item.PartyName = g.Party.Name
	}
	return item
}
