version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupword
    - errcheck
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - perfsprint
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
    gosec:
      excludes:
        - G114 # ListenAndServe is used for internal APIs only
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Relax noisy linters for test files.
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
