/**
 * Curated gallery content for the public Photos page.
 *
 * The image assets are pre-generated and committed under app/assets/gallery by
 * scripts/build-gallery-photos.sh and scripts/build-story-gallery-photos.sh
 * (metadata stripped, resized, AVIF + a JPEG fallback). This module pairs those
 * fingerprinted URLs with each photo's
 * large-variant dimensions (its aspect ratio) and display order so the gallery
 * can lay itself out (justified rows) and reserve space before the images load.
 *
 * To change which photos appear or their order, run the relevant build script
 * and update GALLERY_MANIFEST below to match its output.
 */

/**
 * Fixed widths (px) of the small AVIF tiles used in the grid. The large lightbox
 * tile (mr-<slug>-lg.avif) caps its LONG edge at 2048 instead, so its width
 * varies by orientation and comes from the manifest (see GALLERY_MANIFEST).
 */
const AVIF_THUMB_WIDTHS = [480, 960] as const;

/**
 * Every generated gallery asset as a build-fingerprinted URL. Vite resolves this
 * glob at build time: keys are the on-disk paths, values the hashed URLs to put
 * in src/srcset. Eager so the map is a plain object, available synchronously.
 */
const assetUrls = import.meta.glob<string>(
  "../../assets/gallery/*.{avif,jpg}",
  {
    eager: true,
    import: "default",
    query: "?url",
  },
);

// Index the URLs by bare filename ("mr-8-960.avif") for lookup by slug + width.
const urlByFile = new Map<string, string>(
  Object.entries(assetUrls).map(([path, url]) => [
    path.slice(path.lastIndexOf("/") + 1),
    url,
  ]),
);

const urlFor = (file: string): string => urlByFile.get(file) ?? "";

interface GalleryManifestEntry {
  /** Asset basename stem, e.g. "mr-8" or "story-9a271cbd20d3". */
  slug: string;
  /** Dimensions of the large (-lg) variant, for aspect ratio and the srcset. */
  width: number;
  height: number;
}

/**
 * The curated photos, in display order, with the dimensions of each one's large
 * (-lg) variant. The personal story photos come first in EXIF capture order.
 * The existing engagement-session exports have no metadata and their originals
 * are unavailable, so that block keeps its prior order after the story photos.
 * Opaque story slugs are generated by scripts/build-story-gallery-photos.sh.
 */
const GALLERY_MANIFEST: GalleryManifestEntry[] = [
  { slug: "story-9a271cbd20d3", width: 2048, height: 1536 },
  { slug: "story-d80850d6cbff", width: 1536, height: 2048 },
  { slug: "story-5451565fea82", width: 1536, height: 2048 },
  { slug: "story-9c466c076a37", width: 1536, height: 2048 },
  { slug: "story-300dbec42505", width: 2048, height: 1551 },
  { slug: "story-4a04fa427f9b", width: 2048, height: 1536 },
  { slug: "story-9960255607e2", width: 1920, height: 1280 },
  { slug: "story-49ff72579b21", width: 2048, height: 1536 },
  { slug: "story-d007bfb9f126", width: 1536, height: 2048 },
  { slug: "story-9ef4d06f94a4", width: 2048, height: 1536 },
  { slug: "story-c5b2c39265db", width: 1536, height: 2048 },
  { slug: "story-048c6406783b", width: 1536, height: 2048 },
  { slug: "story-2b017bb32230", width: 2048, height: 1365 },
  { slug: "story-1173e05a6da7", width: 2048, height: 1536 },
  { slug: "story-48f53dbf55cd", width: 2048, height: 1536 },
  { slug: "story-427dc3ce9d8d", width: 1536, height: 2048 },
  { slug: "story-3ced6694670a", width: 2048, height: 1536 },
  { slug: "story-387c3ac95f4e", width: 1536, height: 2048 },
  { slug: "story-1576985dcd69", width: 2048, height: 1365 },
  { slug: "story-67d844070c55", width: 2048, height: 1365 },
  { slug: "story-f363ca656494", width: 2048, height: 1365 },
  { slug: "story-aee5c389913b", width: 2048, height: 1536 },
  { slug: "story-9709a3c4343b", width: 2048, height: 1365 },
  { slug: "story-6df0cdd32c81", width: 2048, height: 1536 },
  { slug: "story-54fb711d2f65", width: 2048, height: 1536 },
  { slug: "story-b51e472f613d", width: 1365, height: 2048 },
  { slug: "story-b903de51a58b", width: 2048, height: 1536 },
  { slug: "story-d7b714678136", width: 2048, height: 1536 },
  { slug: "story-6679bf08b9e0", width: 2048, height: 1536 },
  { slug: "mr-8", width: 1365, height: 2048 },
  { slug: "mr-9", width: 1365, height: 2048 },
  { slug: "mr-10", width: 1365, height: 2048 },
  { slug: "mr-11", width: 1365, height: 2048 },
  { slug: "mr-19", width: 2048, height: 1365 },
  { slug: "mr-25", width: 2048, height: 1365 },
  { slug: "mr-34", width: 1365, height: 2048 },
  { slug: "mr-40", width: 2048, height: 1365 },
  { slug: "mr-41", width: 1365, height: 2048 },
  { slug: "mr-43", width: 2048, height: 1365 },
  { slug: "mr-47", width: 1365, height: 2048 },
  { slug: "mr-49", width: 2048, height: 1365 },
  { slug: "mr-50", width: 2048, height: 1365 },
  { slug: "mr-53", width: 2048, height: 1365 },
  { slug: "mr-57", width: 2048, height: 1365 },
  { slug: "mr-59", width: 1365, height: 2048 },
  { slug: "mr-60", width: 1365, height: 2048 },
  { slug: "mr-62", width: 2048, height: 1365 },
  { slug: "mr-90", width: 2048, height: 1365 },
  { slug: "mr-91", width: 2048, height: 1365 },
  { slug: "mr-92", width: 2048, height: 1365 },
  { slug: "mr-94", width: 1365, height: 2048 },
  { slug: "mr-95", width: 2048, height: 1365 },
  { slug: "mr-96", width: 1365, height: 2048 },
  { slug: "mr-100", width: 1365, height: 2048 },
  { slug: "mr-101", width: 2048, height: 1365 },
  { slug: "mr-103", width: 1365, height: 2048 },
  { slug: "mr-105", width: 2048, height: 1365 },
  { slug: "mr-107", width: 2048, height: 1365 },
  { slug: "mr-108", width: 2048, height: 1365 },
  { slug: "mr-109", width: 2048, height: 1365 },
  { slug: "mr-113", width: 1365, height: 2048 },
  { slug: "mr-114", width: 2048, height: 1365 },
  { slug: "mr-115", width: 1365, height: 2048 },
];

/**
 * Optional captions, keyed by photo slug. Add an entry to annotate that photo
 * in the lightbox; any photo without an entry simply shows no caption. Kept
 * separate from GALLERY_MANIFEST so regenerating the dimensions never disturbs
 * the hand-written captions.
 *
 * Example:
 *   ["mr-43", "The proposal, minutes after she said yes"],
 */
const CAPTIONS = new Map<string, string>([
  // ["mr-8", "Add a caption like this to annotate a photo"],
]);

export interface GalleryPhoto {
  /** Asset stem; also a stable React key. */
  slug: string;
  /** Alt text describing the photo, used as the image's accessible name. */
  alt: string;
  /** Optional annotation shown in the lightbox; only some photos have one. */
  caption?: string;
  /** Dimensions of the large variant; drives the justified layout + reserves space. */
  width: number;
  height: number;
  /** AVIF `srcset` spanning the width ladder; the browser picks by `sizes`. */
  avifSrcSet: string;
  /** JPEG fallback for browsers without AVIF support. */
  fallbackSrc: string;
}

/** Build the AVIF srcset: the fixed-width thumbnails plus the large variant. */
function avifSrcSet(entry: GalleryManifestEntry): string {
  const thumbs = AVIF_THUMB_WIDTHS.map(
    (w) => `${urlFor(`${entry.slug}-${w}.avif`)} ${w}w`,
  );
  return [...thumbs, `${urlFor(`${entry.slug}-lg.avif`)} ${entry.width}w`].join(
    ", ",
  );
}

/** The gallery, in display order, ready to render. */
export const GALLERY_PHOTOS: GalleryPhoto[] = GALLERY_MANIFEST.map(
  (entry, index) => ({
    slug: entry.slug,
    alt: `Robin and Madeline photo ${index + 1}`,
    caption: CAPTIONS.get(entry.slug),
    width: entry.width,
    height: entry.height,
    avifSrcSet: avifSrcSet(entry),
    fallbackSrc: urlFor(`${entry.slug}-1024.jpg`),
  }),
);
